name: sevis_lakay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  flutter_native_splash: ^2.4.6
  image_picker: ^1.1.2
  http: ^1.4.0
  firebase_storage: ^12.4.7
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bank.png
    - assets/images/club1.png
    - assets/images/eglise.png
    - assets/images/hotel.png
    - assets/images/restoran.png
    - assets/images/sevislakay.png
    - assets/images/avatar.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/sevislakay.png
  android: true
  ios: true